# subinclude("//test/build_defs")

# Test that we can append config fields to a section
# that already exists
go_test(
    name = "plz_init_test",
    srcs = ["plz_init_test.go"],
    deps = [
        "//src/plzinit",
        "//third_party/go:testify",
    ],
)
